ase_resource_group_name                 = "rg-asev3-terraform-ilb-demo-2"
use_existing_vnet_and_subnet            = false
vnet_resource_group_name                = "rg-asev3-terraform-demo"
virtual_network_name                    = "vnet-spoke-asev3"
location                                = "West US 2"
vnet_address_prefixes                   = ["172.16.0.0/16"] 
subnet_name                             = "snet-asev3"
subnet_address_prefixes                 = ["172.16.0.0/24"]
ase_name                                = "asev3-ilb-20211001-2" 
dedicated_host_count                    = 0
zone_redundant                          = false
create_private_dns                      = true
internal_load_balancing_mode            = "Web, Publishing"
network_security_group_name             = "nsg-asev3"
network_security_group_security_rules   = []