# Hand-maintained triage labels - service labels are generated into labeler-issue-triage-generated.yml via 'make generate'
bug:
  - 'panic:'
crash:
  - 'panic:'
v/1.x (legacy):
  - '### AzureRM Provider Version\s+(|azurerm |AzureRM )(|v|V)1\.\d+'
v/2.x (legacy):
  - '### AzureRM Provider Version\s+(|azurerm |AzureRM )(|v|V)2\.\d+'
v/3.x:
  - '### AzureRM Provider Version\s+(|azurerm |AzureRM )(|v|V)3\.\d+'
v/4.x:
  - '### AzureRM Provider Version\s+(|azurerm |AzureRM )(|v|V)4\.\d+'
v/5.x:
  - '### AzureRM Provider Version\s+(|azurerm |AzureRM )(|v|V)5\.\d+'
