run:
  timeout: 60m
  go: 1.18
  modules-download-mode: vendor
  skip-dirs:
    - /sdk/ # Excluding sdk folders as these are externally generated

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - varcheck
    - vet
    - vetshadow
    # - whitespace # Disabled for performance reasons - Ignores cache and takes 12+ minutes to run on the repo for _any_ change

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
  misspell:
    ignore-words:
      - hdinsight
      - exportfs
  nakedret:
    max-func-lines: 40
