# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Pod
metadata:
    name: python
spec:
    containers:
    - name: web
      image: appsvcsample/flaskapp:kube
      # source code for this image repo come from "Get started with Docker Compose" on docker.com
      ports:
      - containerPort: 80
    - name: redis
      image: redis:alpine
