# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Bug Report
description: If something isn't working as expected.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out a bug report.

        If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions).

        Please also note the following potential times when an issue might be in Terraform core:

        * [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
        * [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
        * [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
        * [Registry](https://registry.terraform.io/) issues
        * Spans resources across multiple providers

        If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: community
    attributes:
      label: Community Note
      description: This note is for the community, please leave and skip this.
      value: |
        <!--- Please keep this note for the community --->

        * Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

        <!--- Thank you for keeping this note for the community --->
    validations:
      required: true
  - type: input
    id: terraform
    attributes:
      label: Terraform Version
      description: Which Terraform version are you using?
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: azurerm
    attributes:
      label: AzureRM Provider Version
      description: Which AzureRM Provider version are you using?
      placeholder: 3.0.0
    validations:
      required: true
  - type: input
    id: resource
    attributes:
      label: Affected Resource(s)/Data Source(s)
      description: Please list the affected resources and/or data sources.
      placeholder: azurerm_XXXXX
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Terraform Configuration Files
      description: |
        Please provide a minimal Terraform configuration that can reproduce the issue.

        For large Terraform configs, please use a service like Dropbox and share a link to the ZIP file.
        For security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
      render: hcl
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Debug Output/Panic Output
      description: |
        For long debug logs please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

        To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
      render: shell
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should have happened?
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the steps required to reproduce the issue, e.g.

        1. `terraform apply`
  - type: input
    id: facts
    attributes:
      label: Important Factoids
      description: |
        Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government?
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
