// Copyright IBM Corp. 2014, 2025
// SPDX-License-Identifier: MPL-2.0

package billing_test

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	"github.com/hashicorp/terraform-plugin-testing/tfjsonpath"
	"github.com/hashicorp/terraform-provider-azurerm/internal/acceptance"
	customstatecheck "github.com/hashicorp/terraform-provider-azurerm/internal/acceptance/statecheck"
)

// hand written rather than generated by `tools/generator-tests resourceidentity` - the generator
// requires every identity field to be a top-level attribute, but `billing_account_name` and
// `billing_profile_name` are only exposed here as part of `billing_profile_id`
func TestAccBillingInvoiceSection_resourceIdentity(t *testing.T) {
	skipBillingInvoiceSection(t)

	data := acceptance.BuildTestData(t, "azurerm_billing_invoice_section", "test")
	r := BillingInvoiceSectionResource{}

	checkedFields := map[string]struct{}{
		"billing_account_name": {},
		"billing_profile_name": {},
		"name":                 {},
	}

	data.ResourceIdentityTest(t, []acceptance.TestStep{
		{
			Config: r.basic(data),
			ConfigStateChecks: []statecheck.StateCheck{
				customstatecheck.ExpectAllIdentityFieldsAreChecked(data.ResourceName, checkedFields),
				statecheck.ExpectIdentityValue(data.ResourceName, tfjsonpath.New("billing_account_name"), knownvalue.StringExact(os.Getenv("ARM_BILLING_ACCOUNT"))),
				statecheck.ExpectIdentityValue(data.ResourceName, tfjsonpath.New("billing_profile_name"), knownvalue.StringExact(os.Getenv("ARM_BILLING_PROFILE"))),
				statecheck.ExpectIdentityValueMatchesStateAtPath(data.ResourceName, tfjsonpath.New("name"), tfjsonpath.New("name")),
			},
		},
		data.ImportBlockWithResourceIdentityStep(false),
		data.ImportBlockWithIDStep(false),
	}, false)
}
