// Copyright IBM Corp. 2014, 2025
// SPDX-License-Identifier: MPL-2.0

package scaffold

import (
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-provider-azurerm/internal/tools/scaff/ir"
)

// EmitOptions carries the resolution inputs recorded in the generated mapping so
// `scaff regen` can re-resolve the resource without additional arguments.
type EmitOptions struct {
	ResourceName string // terraform name without the provider prefix, e.g. "redhat_openshift_cluster"
	ARMType      string
	Service      string
	Resource     string // Pandora resource key
	GenResource  bool
	List         bool
	DataSource   bool
}

// Emit renders the schema-customization mapping for a freshly resolved IR: a
// header recording the resolution inputs, followed by one `attribute` block per
// schema property (top-level and nested) pre-filled with its current mapping so
// the file is a complete, editable view of the generated schema.
func Emit(res *ir.ResourceIR, opts EmitOptions) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Schema customization for %s.\n", res.TerraformType)
	sb.WriteString("#\n")
	sb.WriteString("# Generated by `scaff generate`. Rename (tf_name), drop (remove = true) or adjust\n")
	sb.WriteString("# attributes below, then run `scaff regen -file <this file> -overwrite` to\n")
	sb.WriteString("# regenerate. Attributes are addressed by their stable source path (the API JSON\n")
	sb.WriteString("# path) so edits survive regeneration.\n\n")

	writeHeaderAttr(&sb, "resource_name", opts.ResourceName)
	if opts.ARMType != "" {
		writeHeaderAttr(&sb, "arm_type", opts.ARMType)
	}
	if opts.Service != "" {
		writeHeaderAttr(&sb, "service", opts.Service)
	}
	if opts.Resource != "" {
		writeHeaderAttr(&sb, "pandora_resource", opts.Resource)
	}
	if res.APIVersion != "" {
		writeHeaderAttr(&sb, "api_version", res.APIVersion)
	}
	writeHeaderAttr(&sb, "go_name", res.Name)
	writeHeaderAttr(&sb, "servicepackage", res.ServicePackage)
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "gen_resource = %t\n", opts.GenResource)
	fmt.Fprintf(&sb, "list         = %t\n", opts.List)
	fmt.Fprintf(&sb, "data_source  = %t\n\n", opts.DataSource)

	for _, p := range res.TopLevel {
		writeAttribute(&sb, p)
	}
	for _, b := range res.Blocks {
		fmt.Fprintf(&sb, "# --- block %s ---\n", b.Name)
		for _, p := range b.Properties {
			writeAttribute(&sb, p)
		}
	}

	return sb.String()
}

func writeHeaderAttr(sb *strings.Builder, key, val string) {
	fmt.Fprintf(sb, "%-14s = %q\n", key, val)
}

// writeAttribute renders a single `attribute` block reflecting the property's
// current schema mapping. Only flags that are set are emitted, so editing is
// additive.
func writeAttribute(sb *strings.Builder, p *ir.Property) {
	fmt.Fprintf(sb, "attribute %q {\n", p.SourcePath)
	fmt.Fprintf(sb, "  tf_name = %q\n", p.TFName)
	if p.Required {
		sb.WriteString("  required = true\n")
	}
	if p.Optional {
		sb.WriteString("  optional = true\n")
	}
	if p.Computed {
		sb.WriteString("  computed = true\n")
	}
	if p.ForceNew {
		sb.WriteString("  force_new = true\n")
	}
	if p.Sensitive {
		sb.WriteString("  sensitive = true\n")
	}
	sb.WriteString("}\n\n")
}
