// Copyright IBM Corp. 2014, 2025
// SPDX-License-Identifier: MPL-2.0

package scaffold

import (
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-provider-azurerm/internal/tools/scaff/ir"
)

// EmitOptions carries the resolution inputs recorded in the generated mapping so
// `scaff regen` can re-resolve the resource without additional arguments.
type EmitOptions struct {
	ResourceName string // terraform name without the provider prefix, e.g. "redhat_openshift_cluster"
	ARMType      string
	Service      string
	Resource     string // Pandora resource key
	GenResource  bool
	List         bool
	DataSource   bool
}

// Emit renders the schema-customization mapping for a freshly resolved IR: a
// header recording the resolution inputs, followed by one `attribute` block per
// schema property (top-level and nested) pre-filled with its current mapping so
// the file is a complete, editable view of the generated schema.
func Emit(res *ir.ResourceIR, opts EmitOptions) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# Schema customization for %s.\n", res.TerraformType)
	sb.WriteString("#\n")
	sb.WriteString("# Generated by `scaff generate`. Rename (tf_name), drop (remove = true) or adjust\n")
	sb.WriteString("# attributes below, then run `scaff regen -file <this file> -overwrite` to\n")
	sb.WriteString("# regenerate. Attributes are addressed by their stable source path (the API JSON\n")
	sb.WriteString("# path) so edits survive regeneration.\n\n")

	writeHeaderAttr(&sb, "resource_name", opts.ResourceName)
	if opts.ARMType != "" {
		writeHeaderAttr(&sb, "arm_type", opts.ARMType)
	}
	if opts.Service != "" {
		writeHeaderAttr(&sb, "service", opts.Service)
	}
	if opts.Resource != "" {
		writeHeaderAttr(&sb, "pandora_resource", opts.Resource)
	}
	if res.APIVersion != "" {
		writeHeaderAttr(&sb, "api_version", res.APIVersion)
	}
	writeHeaderAttr(&sb, "go_name", res.Name)
	writeHeaderAttr(&sb, "servicepackage", res.ServicePackage)
	sb.WriteString("\n")
	fmt.Fprintf(&sb, "gen_resource = %t\n", opts.GenResource)
	fmt.Fprintf(&sb, "list         = %t\n", opts.List)
	fmt.Fprintf(&sb, "data_source  = %t\n\n", opts.DataSource)

	// Build a map from BlockModel.Name → the dot-separated tf_name prefix that
	// addresses it from the top level. This lets block properties be emitted
	// with a fully-qualified tf_name (e.g. "encryption.key_vault_properties.keyvault_uri")
	// so the generated file is immediately usable as a path-qualified rename target.
	blockPrefix := buildBlockPrefixes(res)

	for _, p := range res.TopLevel {
		if p.SourcePath == "" {
			continue
		}
		writeAttribute(&sb, p, "")
	}
	for _, b := range res.Blocks {
		fmt.Fprintf(&sb, "# --- block %s ---\n", b.Name)
		prefix := blockPrefix[b.Name]
		for _, p := range b.Properties {
			if p.SourcePath == "" {
				continue
			}
			writeAttribute(&sb, p, prefix)
		}
	}

	return sb.String()
}

// buildBlockPrefixes returns a map from BlockModel.Name to the dot-separated
// tf_name path prefix for that block (e.g. "Encryption" → "encryption",
// "KeyVaultProperties" → "encryption.key_vault_properties"). It walks
// res.TopLevel and recurses into nested blocks so every depth is covered.
func buildBlockPrefixes(res *ir.ResourceIR) map[string]string {
	byName := make(map[string]*ir.BlockModel, len(res.Blocks))
	for _, b := range res.Blocks {
		byName[b.Name] = b
	}

	result := make(map[string]string, len(res.Blocks))

	var walk func(props []*ir.Property, parentPrefix string)
	walk = func(props []*ir.Property, parentPrefix string) {
		for _, p := range props {
			if !p.IsBlock || p.BlockName == "" {
				continue
			}
			var prefix string
			if parentPrefix == "" {
				prefix = p.TFName
			} else {
				prefix = parentPrefix + "." + p.TFName
			}
			result[p.BlockName] = prefix
			if b, ok := byName[p.BlockName]; ok {
				walk(b.Properties, prefix)
			}
		}
	}
	walk(res.TopLevel, "")

	return result
}

func writeHeaderAttr(sb *strings.Builder, key, val string) {
	fmt.Fprintf(sb, "%-14s = %q\n", key, val)
}

// writeAttribute renders a single `attribute` block reflecting the property's
// current schema mapping. Only flags that are set are emitted, so editing is
// additive. blockPrefix is the dot-separated path to the containing block (e.g.
// "encryption.key_vault_properties"); empty string for top-level properties.
func writeAttribute(sb *strings.Builder, p *ir.Property, blockPrefix string) {
	tfName := p.TFName
	if blockPrefix != "" {
		tfName = blockPrefix + "." + p.TFName
	}
	fmt.Fprintf(sb, "attribute %q {\n", p.SourcePath)
	fmt.Fprintf(sb, "  tf_name = %q\n", tfName)
	if p.Required {
		sb.WriteString("  required = true\n")
	}
	if p.Optional {
		sb.WriteString("  optional = true\n")
	}
	if p.Computed {
		sb.WriteString("  computed = true\n")
	}
	if p.ForceNew {
		sb.WriteString("  force_new = true\n")
	}
	if p.Sensitive {
		sb.WriteString("  sensitive = true\n")
	}
	sb.WriteString("}\n\n")
}
