variable azurerm_resource_group_name {}
variable azurerm_resource_group_location {}
variable azurerm_kubernetes_cluster_dns_prefix {}
variable azurerm_kubernetes_cluster_version {}
variable azurerm_kubernetes_cluster_admin_username {}
variable azurerm_kubernetes_cluster_ssh_key {}
variable azurerm_kubernetes_cluster_agent_count {}
variable azurerm_kubernetes_cluster_agent_vm_size {}
variable azurerm_kubernetes_cluster_client_id {}
variable azurerm_kubernetes_cluster_client_secret {}