name: 'Close PRs With Failing CI'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * MON,WED,FRI'

permissions:
  issues: write
  pull-requests: write
  checks: read
  statuses: read

jobs:
  close-failing-ci-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v6
      - name: Process PRs with failing CI
        run: ./scripts/close-failing-ci-prs.sh -o "${{ github.repository_owner }}" -r "${{ github.event.repository.name }}" -t "${{ secrets.GITHUB_TOKEN }}" -l
