---
name: Resource Document Linting

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - ".github/workflows/document-lint.yaml"
      - "internal/services/**"
      - "website/**"
    branches: ["main"]

jobs:
  document-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make document-lint
        continue-on-error: true
      - name: check lint result
        if: failure()
        run: |
            echo "::warning::Document linting failed. Please fix the issues."