---
name: Resource Document Linting

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - ".github/workflows/document-lint.yaml"
      - "internal/services/**"
      - "website/**"
    branches: ["main"]

jobs:
  document-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make document-lint
        continue-on-error: true
      - name: check lint result
        if: failure()
        run: |
            echo "::warning::Document linting failed. Please fix the issues."