---
name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write

jobs:
  remove-stale:
    uses: ./.github/workflows/remove-issue-label.yml
    with:
      label-name: "stale"
  remove-waiting-response-from-issue:
    uses: ./.github/workflows/remove-issue-label.yml
    if: ${{ !github.event.issue.pull_request }}
    with:
      label-name: "waiting-response"
  remove-waiting-response-from-pr:
    uses: ./.github/workflows/remove-issue-label.yml
    if: (github.event.issue.pull_request && github.actor == github.event.issue.user.login)
    with:
      label-name: "waiting-response"

  pull_request_comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && endsWith(github.event.comment.body, '/wr')
    steps:
      - uses: actions/github-script@d746ffe35508b1917358783b479e04febd2b8f71 # v9
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["waiting-response"]
            })