---
name: "Pull Request Triage"

permissions:
  pull-requests: write
  issues: write

on: [pull_request_target]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4.2.0
      with:
        configuration-path: .github/labeler-pull-request-triage.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: CodelyTV/pr-size-labeler@54ef36785e9f4cb5ecf1949cfc9b00dbb621d761 # v1.8.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/XS'
        xs_max_size: '30'
        s_label: 'size/S'
        s_max_size: '60'
        m_label: 'size/M'
        m_max_size: '150'
        l_label: 'size/L'
        l_max_size: '300'
        xl_label: 'size/XL'
        message_if_xl: ''
