---
name: Pull Request Type

permissions:
  pull-requests: write

on: 
  pull_request_target:
    types: [opened, edited]

jobs:
  pr_triage_label_type:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      continue-on-error: true
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-pull-request-triage-type.yml
        enable-versioned-regex: 0