---
name: TeamCity Config Test

permissions:
  contents: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/teamcity-test.yaml'
      - '!.teamcity/components/generated/**'
      - '!.teamcity/target/**'
      - '.teamcity/**'

concurrency:
  group: 'tctest-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  teamcity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v6
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: make teamcity-test
